schitts/lecarrou/app/api/urls.py
from django.urls import path
from .views import UserRecordView
from rest_framework.authtoken.views import obtain_auth_token
from rest_framework import routers

# app_name = 'api'
# urlpatterns = [
#     path('user/', UserRecordView.as_view(), name='users'),
#     path('api-token-auth/', obtain_auth_token, name='api-token-auth'),
# ]

from django.conf.urls import url 
from api import views 

app_name = 'api' 
urlpatterns = [ 
    path('user/', UserRecordView.as_view(), name='users'),
    path('api-token-auth/', obtain_auth_token, name='api-token-auth'),
    path('tutorials/', views.tutorial_list),
    path('tutorials/<int:pk>', views.tutorial_detail),
    path('tutorials/published/', views.tutorial_list_published)
]

schitts/lecarrou/app/cafe/urls.py
from django.urls import path
from . import views
from cafe.views import OrderCreateView, OrderUpdateView, DashboardView
from django.contrib.auth.decorators import login_required, permission_required

app_name = 'cafe' 
urlpatterns = [ 
    path('orders/', views.index, name='index'),
    path('orders/tables/', views.tables, name='tables'),
    path('orders/edit/', login_required(OrderCreateView.as_view()), name='edit_order'),
    path('orders/update/<int:pk>/', login_required(OrderUpdateView.as_view()), name='update_order'),
    path('served/', views.served, name='served'),
    path('bill/', views.bill, name='bill'),
    path('paiement/', views.paiement, name='paiement'),
    path('ticket/<int:pk>', views.ticket, name='ticket'),
    path('comment/index/', views.comment_index, name='comment_index'),
    path('comment/', views.comment, name='comment'),
    path('dashboard/', login_required(views.DashboardView.as_view()), name='dashboard'),
    path('dashboard_data/', views.dashboard_data, name='dashboard_data'),
]

schitts/lecarrou/app/cafe/models.py
from django.db import models
# Allow logical deleting (https://buildmedia.readthedocs.org/media/pdf/django-safedelete/latest/django-safedelete.pdf)
from safedelete.models import SafeDeleteModel, SOFT_DELETE, SOFT_DELETE_CASCADE
# Trace all actions on the database (https://django-simple-history.readthedocs.io/en/latest/)
from simple_history.models import HistoricalRecords
# https://simpleisbetterthancomplex.com/tutorial/2016/07/22/how-to-extend-django-user-model.html#onetoone
from django.contrib.auth.models import User
from django.utils import timezone
from django.core.mail import send_mail
import random, string
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.db.models import Count

class Tables(SafeDeleteModel):
    """ A class to create a new table instance in the Schitt's Creek Cafe Tropical. """

    _safedelete_policy = SOFT_DELETE_CASCADE
    table_id = models.AutoField("Table id", primary_key = True)
    number = models.IntegerField("Number of customer", null=True, blank=True)
    available = models.BooleanField("Available")
    created_at = models.DateTimeField("Date created", auto_now_add = True)
    log = HistoricalRecords()

    class Meta:

        db_table = 'Tables'
        verbose_name_plural = 'Tables'
        ordering = ['table_id']

    def __str__(self):

        return f"Table {self.table_id} - {self.number} person(s)"


class Orders_Menus(SafeDeleteModel):
    """ A class to create a new Orders_Menus instance in the Schitt's Creek Cafe Tropical. """
    
    _safedelete_policy = SOFT_DELETE_CASCADE
    order = models.ForeignKey("Orders", on_delete = models.CASCADE)
    menu = models.ForeignKey("Menus", on_delete = models.CASCADE)
    cooking = models.IntegerField("Cooking", default=0, null=True, blank=True)
    tone = models.IntegerField("Tone", default=0, null=True, blank=True)
    log = HistoricalRecords()

    class Meta:

        db_table = 'Orders_Menus'


class Customers_Orders_Comments(SafeDeleteModel):
    """ A class to create a new Customers_Orders instance in the Schitt's Creek Cafe Tropical. """
    
    _safedelete_policy = SOFT_DELETE_CASCADE
    order = models.ForeignKey("Orders", on_delete = models.CASCADE)
    customer = models.ForeignKey("Customers", on_delete = models.CASCADE)
    comment = models.OneToOneField("Comments", on_delete = models.CASCADE, null=True, blank=True)
    log = HistoricalRecords()

    class Meta:

        db_table = 'Customers_Orders_Comments'

class Orders(SafeDeleteModel):
    """ A class to create a new order instance in the Schitt's Creek Cafe Tropical. """

    _safedelete_policy = SOFT_DELETE_CASCADE
    order_id = models.AutoField("Order id", primary_key = True)
    table = models.ForeignKey(Tables, on_delete = models.CASCADE) # related table
    customers = models.IntegerField("Number of customer", null=True, blank=True)
    split_bill = models.IntegerField("Split bill", null=True, blank=True)
    delivered = models.BooleanField("Delivered", null=True, blank=True, default=False)
    paid = models.BooleanField("Available", null=True, blank=True, default=False)
    created_at = models.DateTimeField("Date created", auto_now_add = True)
    log = HistoricalRecords()

    class Meta:

        db_table = 'Orders'
        verbose_name_plural = 'Orders'
        ordering = ['order_id']

    def __str__(self):

        return f"{self.order_id}"


class Menus(SafeDeleteModel):
    """ A class to create a new Menu instance in the Schitt's Creek Cafe Tropical. """

    _safedelete_policy = SOFT_DELETE_CASCADE
    menu_id = models.AutoField("Order id", primary_key = True)
    orders = models.ManyToManyField("Orders", through = Orders_Menus, related_name = "OrdersMenus") # Orders_Menus
    item = models.CharField("Name", max_length = 100, null=True, blank=True)
    price = models.DecimalField("Price", max_digits=5, decimal_places=2, null=True, blank=True)
    last_order_date = models.DateTimeField("Last order date", null=True, blank=True)
    conservation = models.IntegerField("Conservation (min)", default=0, null=True, blank=True)
    available = models.BooleanField("Available", null=True, blank=True)
    created_at = models.DateTimeField("Date created", auto_now_add = True)
    log = HistoricalRecords()

    class Meta:

        db_table = 'Menus'
        verbose_name_plural = 'Menus'
        ordering = ['menu_id']

    def __str__(self):

        return f"{self.item}"


class Customers(SafeDeleteModel):
    """ A class to create a new Customer instance in the Schitt's Creek Cafe Tropical. """

    _safedelete_policy = SOFT_DELETE_CASCADE
    customer_id = models.AutoField("Customer id", primary_key = True)
    orders = models.ManyToManyField(Orders, through = Customers_Orders_Comments, related_name = "CustomersOrdersComments") #, related_name = "Customers_Orders") # Customers_Orders
    user = models.OneToOneField(User, on_delete = models.CASCADE)
    customer_type = models.IntegerField("Customer type", default=0, null=True, blank=True)
    drink_preferences = models.IntegerField("Drink preferences", default=0, null=True, blank=True)
    food_preferences = models.IntegerField("Food preferences", default=0, null=True, blank=True)
    created_at = models.DateTimeField("Date created", auto_now_add = True)
    log = HistoricalRecords()

    class Meta:

        db_table = 'Customers'
        verbose_name_plural = 'Customers'
        ordering = ['customer_id']

    @property
    def number_orders(self):
        """ return the number of orders for a given customer"""
        # SELECT order_id,count(*) FROM "Customers_Orders_Comments" WHERE customer_id=1 GROUP BY order_id ORDER BY order_id;
        return self.orders.all().annotate(num_orders=Count('order_id')).count()

    def number_orders_year(self,year):
        """ return the number of orders for a given customer and a given year"""
        return self.orders.filter(created_at__year=year).annotate(num_orders=Count('order_id')).count()        

    def __str__(self):

        return f"{self.customer_id}"

# https://simpleisbetterthancomplex.com/tutorial/2017/02/18/how-to-create-user-sign-up-view.html#sign-up-with-profile-model
@receiver(post_save, sender=User)
def create_user_customers(sender, instance, created, **kwargs):
    if created:
        Customers.objects.create(user=instance)


class Comments(SafeDeleteModel):
    """ A class to create a new Comment instance in the Schitt's Creek Cafe Tropical. """

    _safedelete_policy = SOFT_DELETE_CASCADE
    comment_id = models.AutoField("Customer id", primary_key = True)
    title = models.CharField("Title", max_length = 50, null=True, blank=True)
    comment = models.CharField("Comment", max_length = 250, null=True, blank=True)
    rate = models.IntegerField("Rate", null=True, blank=True)
    like = models.IntegerField("Likes", null=True, blank=True)
    dislike = models.IntegerField("Dislikes", null=True, blank=True)
    created_at = models.DateTimeField("Date created", auto_now_add = True)
    log = HistoricalRecords()

    class Meta:

        db_table = 'Comments'
        verbose_name_plural = 'Comments'
        ordering = ['comment_id']

    def __str__(self):

        return f"{self.comment_id}"

schitts/lecarrou/app/cafe/forms.py
from django import forms
from cafe.models import Tables, Orders, Menus, Orders_Menus, Customers, Customers_Orders_Comments, Comments

from django.forms.models import ModelForm, inlineformset_factory
from django.forms import BaseInlineFormSet
from django.forms import modelformset_factory
from django.forms import ModelChoiceField
from django.forms.models import ModelChoiceIterator
from django.forms.fields import ChoiceField
from django.core.exceptions import ValidationError
from django.db.models import Q
from django.utils import timezone
from datetime import datetime, timedelta 
from dateutil.relativedelta import *

class TableEditForm(forms.ModelForm):

    def __init__(self, request, *args, **kwargs):
        super(TableEditForm, self).__init__(*args, **kwargs)
        TABLES = [(table.table_id,'Table n°'+str(table.table_id)) for table in Tables.objects.filter(available = True)]
        TABLES.insert(0, (None, ''))
        self.fields["table_id"] = forms.ChoiceField(label = "Table number", widget = forms.Select, choices = TABLES)
    
    class Meta:
        model = Tables
        fields = ('table_id',)


class OrderCreateForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop("request")
        super(OrderCreateForm, self).__init__(*args, **kwargs)
        TABLES = Tables.objects.filter(available = True)

        self.fields["table"] = forms.ModelChoiceField(queryset = TABLES, label = "Table", widget = forms.Select())
        self.fields["customers"] = forms.IntegerField(label = "Customers number", widget = forms.Select())

    class Meta:
        model = Orders
        fields = ('order_id','table','customers',)


class OrderUpdateForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop("pk")
        super(OrderUpdateForm, self).__init__(*args, **kwargs)
        ORDER = Orders.objects.get(order_id = self.request)
        print('pk',self.request)
        print('ORDER.customers',ORDER.customers)
        TABLES = Tables.objects.filter(available = True)
        CUSTOMERS = Customers.objects.all()
        self.fields["table"] = forms.ModelChoiceField(queryset = TABLES, label = "Table", widget = forms.Select(attrs={'readonly':'readonly'}), initial = ORDER.table)
        self.fields["customers"] = forms.IntegerField(label = "Customers number", initial = ORDER.customers)

    class Meta:
        model = Orders
        fields = ('order_id','table','customers',)


COOKING = [(None,''),(1,'1'),(2,'2'),(3,'3'),(4,'4'),(5,'5'),(6,'6'),(7,'7'),(8,'8'),(9,'9'),(10,'10')]# TO DO: choice list to be conditionned on selected table
TONES = [(None,''),(1,'Angry'),(2,'Happy'),(3,'Overwhelmed'),(4,'Pregnant'),(5,'Moody'),(6,'Bored'),(7,'Excited')] # TO DO: choice list to be conditionned on thesaurus

MenuFormset = inlineformset_factory(
    Orders, Orders_Menus, 
    fields=('cooking','menu','tone'),
    widgets={
        'cooking': forms.Select(choices = COOKING),
        'tone': forms.Select(choices = TONES),
        'menu': forms.Select(),
    },
    extra=1,
    can_delete=True,
    
)

UpdateMenuFormset = inlineformset_factory(
    Orders, Orders_Menus,  
    fields=('cooking','menu','tone'),
    widgets={
        'cooking': forms.Select(choices = COOKING),
        'tone': forms.Select(choices = TONES),
        'menu': forms.Select(),
    },
    extra=0,
    can_delete=True,
)

CustomerFormset = inlineformset_factory(
    Orders, Customers_Orders_Comments,
    fields=('order','customer','comment'),
    extra=1,
    can_delete=True,
)



class CommentIndexForm(forms.Form):
    def __init__(self, request, *args, **kwargs):
        super(CommentIndexForm, self).__init__(*args, **kwargs)
        self.fields["order_id"] = forms.IntegerField(label = "Order id", widget = forms.TextInput())
    

class CommentForm(forms.ModelForm):

    def __init__(self, request, *args, **kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)
        self.request = request
        self.user = request.user.id
        print('user',self.user)

    order_id = forms.IntegerField(label = "Order number (available on your bill)", widget = forms.TextInput())
    title = forms.CharField(label='Title')
    comment = forms.CharField(widget=forms.Textarea)
    rate = forms.ChoiceField(label = "How would you rate your experience at Schitt\'s Creek Cafe Tropical? ", widget = forms.Select(),choices = [(None,''),(0,'Bad experience'),(1,'Quite good experience'),(2,'Good experience'),(3,'Very good experience')])

    def clean(self):
        cleaned_data = super(CommentForm, self).clean()
        c_id = Customers.objects.get(user = self.user).customer_id
        if Customers_Orders_Comments.objects.filter(Q(customer_id = c_id) & Q(order_id = self.data.get('order_id')) & ~Q(comment_id = None)).exists():
            raise forms.ValidationError('You have already add a comment for this order. You can only add one comment per order.')


    class Meta:
        model = Comments
        fields = ('order_id','title','comment','rate')
    
    def clean_order_id(self):
        data = self.cleaned_data['order_id']
        if not Orders.objects.filter(Q(order_id = data) & Q(paid = True)).exists():
            raise forms.ValidationError('This order id does not exist. Please check your bill.')
        return data


# formulaire non lié à un model
class DashboardForm(forms.Form):

    def __init__(self, *args, **kwargs):
        super(DashboardForm, self).__init__(*args, **kwargs)
        orders = Orders.objects.all()
        self.fields["start_date"] = forms.DateField(
            label = "Start date", 
            widget=forms.DateInput(format='%d/%m/%Y',attrs={'placeholder': '01/01/2021'}),
            input_formats=['%d/%m/%Y',],
            required=True, initial=timezone.now()+relativedelta(months=-6)
        )
        # empêche l'autocomplétion
        self.fields['start_date'].widget.attrs.update({
            'autocomplete': 'off'
        })
        self.fields["end_date"] = forms.DateField(
            label = "End date", 
            widget=forms.DateInput(format='%d/%m/%Y',attrs={'placeholder': '01/01/2021'}),
            input_formats=['%d/%m/%Y',],
            required=True, initial=timezone.now()
        )
        self.fields['end_date'].widget.attrs.update({
            'autocomplete': 'off'
        })
    
    def clean(self):
        cleaned_data = super().clean()
        start_date = cleaned_data.get("start_date")
        end_date = cleaned_data.get("end_date")
        if start_date and end_date:
            if start_date > end_date:
                raise ValidationError('Start date can not be posterior to end date')
    
    def clean_start_date(self):
        data = self.cleaned_data['start_date']
        entrydate = datetime.datetime.strptime(str(data), "%Y-%m-%d")
        currentdate = datetime.datetime.now()
        if entrydate > currentdate:
            raise forms.ValidationError(_("Please check entry date"))
        return data
    
    def clean_end_date(self):
        data = self.cleaned_data['end_date']
        entrydate = datetime.datetime.strptime(str(data), "%Y-%m-%d")
        currentdate = datetime.datetime.now()
        if entrydate > currentdate:
            raise forms.ValidationError(_("Please check entry date"))
        return data

schitts/lecarrou/app/cafe/templates/cafe/comment_index.html
{% extends 'layouts/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block extrahead %}{% endblock %}
{% block title %}Comment | Schitt's Creek Cafe Tropical{% endblock %}
{% block content %}
<style>
.addspace {
    padding-bottom:10px;
}

</style>
<div class='container'>
    <br>
    <div class="row">
        <div class="col-sm-11"><h3>Comments</h3></div>
        <div class="col-sm-1"><h3><a class="nav-link" style="color:black" href="{% url 'cafe:comment' %}"><i class="fa fa-comment" aria-hidden="true"></i>
            </a></h3></div>
    </div>


    <br>
    <br>
    <br>
    {% for comment in comments %}
        <div class="container">
           <div class="row">
                <div class="col-sm-10">
                    <span style="font-weight:bold">{{ comment.customer.user.username }}</span> - <span style="font-style:italic">Published on: {{ comment.comment.created_at }}</span>
                </div>
                <div class="col-sm-1">
                {% if comment.comment.rate == 0 %}
                    <i class="fa fa-star-o" aria-hidden="true"></i>
                    <i class="fa fa-star-o" aria-hidden="true"></i>
                    <i class="fa fa-star-o" aria-hidden="true"></i>
                {% elif comment.comment.rate == 1 %}
                    <i class="fa fa-star" aria-hidden="true"></i>
                    <i class="fa fa-star-o" aria-hidden="true"></i>
                    <i class="fa fa-star-o" aria-hidden="true"></i>
                {% elif comment.comment.rate == 2 %}
                    <i class="fa fa-star" aria-hidden="true"></i>
                    <i class="fa fa-star" aria-hidden="true"></i>
                    <i class="fa fa-star-o" aria-hidden="true"></i>
                {% elif comment.comment.rate == 3 %}
                    <i class="fa fa-star" aria-hidden="true"></i>
                    <i class="fa fa-star" aria-hidden="true"></i>
                    <i class="fa fa-star" aria-hidden="true"></i>
                {% endif %}
                </div>
                <div class="col-sm-1">
                    <i class="fa fa-thumbs-o-up" aria-hidden="true"></i>
                </div>
            </div>
        </div>
        <div class="dropdown-divider"></div>
        <div class="container">
            <div class="row" style="background-color: #9cb58d; padding:10px">
                <div class="col-sm-12">
                    <h4>{{ comment.comment.title }}</h4>
                    {{ comment.comment.comment }}
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12">
                    <span>Date of the visit: {{ comment.order.created_at }}</span>
                </div>
            </div>
        </div>
        <br><br>
    {% endfor %}




    <!-- Modal -->
    <div class="modal fade" id="comment_edit" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLongTitle">Schitt's Creek Cafe Tropical</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            </div>
            <div class="modal-body">
            Do you valid comment?
            </div>
            <div class="modal-footer">
            <button id="comment_button_no" type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
            <button id="comment_button_yes" data-redirect-url="" type="button" class="btn btn-primary">Yes</button>
            </div>
        </div>
        </div>
    </div>
</div>

{% endblock %}
{% block extrabody %}
<script type="text/javascript">
	var popup_comment;

	$('.link-formset').formset({
        addText: 'Add',
		deleteText: 'Delete',
		prefix: '{{ menu.prefix }}',
        //hideLastAddForm: 'true'
    });


	$(document).ready(function() {


		var prevent = false;

		$("#commenteditform").submit(function(event) {
			if(!prevent){
				event.preventDefault();
			}
			
        	popup_comment = $(this);
        	$('#comment_edit').modal('show');

    	});

		$("body")
    	.on('click','#comment_button_yes',function(event){
        	prevent = true;
        	popup_comment.submit();
    	})

    });

</script>
{% endblock %}

schitts/lecarrou/app/cafe/templates/cafe/order.html
{% extends 'layouts/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block extrahead %}{% endblock %}
{% block title %}Order | Schitt's Creek Cafe Tropical{% endblock %}
{% block content %}
<style>
.addspace {
    padding-bottom:10px;
}

</style>
<div class='container'>

	<div id="template" style="display: none;">{{ template }}</div>
    <br>
    <br>
    <br>
    <form id="ordereditform" method="POST" class="post-form" data-tables="{{ tables }}">
	    {% csrf_token %}
        {% comment %} {{ form|crispy }} {% endcomment %}
        <h2>Order</h2><br><br>
		<div class="form-row">
			<div class="form-group col-md-6 mb-0">
				{{ form.table|as_crispy_field }}
			</div>
			<div class="form-group col-md-6 mb-0">
				{{ form.customers|as_crispy_field }}
			</div>
		</div>

		<br>
		<!-- {{ menu|crispy }} --> <!-- curieusement si j'enlève cette ligne le style crispy disparait -->
		<!-- subform Menu -->
		{{ menu.management_form|crispy }}
		
			{% if menu.non_form_errors %}
			<div id="non_form_errors" class="alert alert-block alert-danger" >
				{% for error in menu.non_form_errors %}
					<ul>
						<li>{{ error|escape }}</li>
					</ul>
				{% endfor %}
			</div>
			{% endif %}	
	    
		<div class="row">
			<div class="col-4"><p>Item</p></div>
			<div class="col-3"><p>Cooking</p></div>
            <div class="col-4"><p>Tone</p></div>
			<div class="col-1"><p></p></div>
		</div>		
		{% for menu_form in menu %}
		
		<div class="row link-formset addspace">
            <div class="col-4">
					
					{{ menu_form.menu }}
					{% if menu_form.menu.errors %}
						{% for error in menu_form.menu.errors %}
						<span style="color:red;">{{ error|escape }}</span>
						{% endfor %}
					{% endif %}
            
            </div>
			{% if menu_form.instance.pk %}{{ menu_form.DELETE }}{% endif %}
			<div class="col-3">
					
					{{ menu_form.cooking }}
					{% if menu_form.cooking.errors %}
						{% for error in menu_form.cooking.errors %}
						<span style="color:red;">{{ error|escape }}</span>
						{% endfor %}
					{% endif %}

			</div>
			<div class="col-4">

					{{ menu_form.tone }}
					{% if menu_form.tone.errors %}
						{% for error in menu_form.tone.errors %}
						<span style="color:red;">{{ error|escape }}</span>
						{% endfor %}
					{% endif %}

			</div>
			<div class="hidden">{{ menu_form.id }}</div>
            
		</div>

		{% endfor %}
		<br><br>
		<!-- end subform Menu -->



        <br><br>
		<button id="ajouter_projet" class="btn btn-primary" type="submit" style="width: 100px;">Save</button>
		<a data-modal data-target="" class="btn btn-danger" href="{% url 'cafe:index' %}" style="width: 100px;">Cancel</a>
	</form>


    <!-- Modal -->
    <div class="modal fade" id="order_edit" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLongTitle">Schitt's Creek Cafe Tropical</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            </div>
            <div class="modal-body">
            Do you valid order?
            </div>
            <div class="modal-footer">
            <button id="order_button_no" type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
            <button id="order_button_yes" data-redirect-url="" type="button" class="btn btn-primary">Yes</button>
            </div>
        </div>
        </div>
    </div>
</div>

{% endblock %}
{% block extrabody %}



<script type="text/javascript">
	var popup_order;
	var menunumber_subform; // nombre de sous formulaire affichés (1 par défaut puis ajout sur click .add-row)
	var select_app;
	var select_access;


	$('.link-formset').formset({
        addText: 'Add',
		deleteText: 'Delete',
		prefix: '{{ menu.prefix }}',
        //hideLastAddForm: 'true'
    });


	$(document).ready(function() {


		var prevent = false;
		var menunumber_subform = menunumber(); // nombre de sous formulaire affichés (1 par défaut au chargement de la page)
        var menuinitialnumber_subform = menuinitialnumber();
        console.log($("#template").text())
		if($("#template").text() == "update"){
			// to add empty formset (by default, it clone previous frormset with its values)
			$('.add-row').on('click',function(event){
				i = menuinitialnumber_subform;
				$('#id_orders_menus_set-'+i+'-menu').val('');
				$('#id_orders_menus_set-'+i+'-cooking').val('');
				$('#id_orders_menus_set-'+i+'-tone').val('');
				menuinitialnumber_subform++;
			})
		}


        var tables = {{ tables }}
        //https://codepen.io/Lighty_46/pen/gpLZWx?editors=1010
        // When an option is changed, search the above for matching choices
        $('#id_table').on('change', function() {
			
            // Set selected option as variable
            var selectValue = $(this).val();

            // Empty the target field
            $('#id_customers').empty();
            
            // For each choice in the selected option
            for (i = 0; i < tables[selectValue].length; i++) {
                // Output choice in the target field
                $('#id_customers').append("<option value='" + tables[selectValue][i] + "'>" + tables[selectValue][i] + "</option>");
			}
			
        });

		$("#ordereditform").submit(function(event) {
			if(!prevent){
				event.preventDefault();
			}
			
        	popup_order = $(this);
        	$('#order_edit').modal('show');

    	});

		$("body")
    	.on('click','#order_button_yes',function(event){
        	prevent = true;
        	popup_order.submit();
    	})


    });


	// déterminer le nombre de sous-formulaire menu présents sur la page
	function menunumber() {
        return $("#id_orders_menus_set-TOTAL_FORMS").val();
    };
	// déterminer le nombre de sous-formulaire menu présents sur la page
	function menuinitialnumber() {
        return $("#id_orders_menus_set-INITIAL_FORMS").val();
    };

</script>
{% endblock %}

schitts/lecarrou/app/cafe/templates/cafe/table.html
{% extends 'layouts/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block extrahead %}{% endblock %}
{% block title %}Tables | Schitt's Creek Cafe Tropical{% endblock %}
{% block content %}

<div class='container'>
    <br>        
    <br>
    <h1>Choose a table</h1>
    <br>
    <br>
    <br>
    <form id="tableeditform" method="POST" class="post-form">
	    {% csrf_token %}
        {{ form|crispy }}
		<button id="ajouter_projet" class="btn btn-primary" type="submit" style="width: 100px;">Save</button>
		<a data-modal data-target="" class="btn btn-danger" href="{% url 'cafe:index' %}" style="width: 100px;">Cancel</a>
	</form>
</div>

{% endblock %}
{% block extrabody %}
<!--DataTable
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.css">
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css">
DataTable-->



<script></script>
{% endblock %}