schitts/lecarrou/app/api/urls.py
from django.urls import path
from .views import UserRecordView
from rest_framework.authtoken.views import obtain_auth_token
from rest_framework import routers

# app_name = 'api'
# urlpatterns = [
#     path('user/', UserRecordView.as_view(), name='users'),
#     path('api-token-auth/', obtain_auth_token, name='api-token-auth'),
# ]

from django.conf.urls import url 
from api import views 

app_name = 'api' 
urlpatterns = [ 
    path('user/', UserRecordView.as_view(), name='users'),
    path('api-token-auth/', obtain_auth_token, name='api-token-auth'),
    path('tutorials/', views.tutorial_list),
    path('tutorials/<int:pk>', views.tutorial_detail),
    path('tutorials/published/', views.tutorial_list_published)
]

schitts/lecarrou/app/cafe/urls.py
from django.urls import path
from . import views
from cafe.views import OrderCreateView, OrderUpdateView, DashboardView
from django.contrib.auth.decorators import login_required, permission_required

app_name = 'cafe' 
urlpatterns = [ 
    path('orders/', views.index, name='index'),
    path('orders/tables/', views.tables, name='tables'),
    path('orders/edit/', login_required(OrderCreateView.as_view()), name='edit_order'),
    path('orders/update/<int:pk>/', login_required(OrderUpdateView.as_view()), name='update_order'),
    path('served/', views.served, name='served'),
    path('bill/', views.bill, name='bill'),
    path('paiement/', views.paiement, name='paiement'),
    path('ticket/<int:pk>', views.ticket, name='ticket'),
    path('comment/index/', views.comment_index, name='comment_index'),
    path('comment/', views.comment, name='comment'),
    path('dashboard/', login_required(views.DashboardView.as_view()), name='dashboard'),
    path('dashboard_data/', views.dashboard_data, name='dashboard_data'),
]

schitts/lecarrou/app/registration/urls.py
from django.urls import path
from . import views
# from django.contrib.auth import views
from registration import views


app_name='registration'
urlpatterns = [
    # path('login/', views.login, name='login'),
    # path('logout/', views.logout, name='logout'),
    path('', views.signup, name='signup'),
    path('profile/', views.profile, name='profile'),
]

schitts/lecarrou/app/templates/layouts/_footer.html
<footer class="footer" style="background-color:#9cb58d;">
<div style="color: #3c512f; position:absolute; z-index: 1; padding-left:10px; font-weight:bold;">{{ environment }}</div>
    <div class="container" style="text-align: center;">
        <span class="text-muted">© {% now 'Y' %} Copyright :
            <a href="https://cv-lecarrou.netlify.app" target="_blank"> Jérôme Le Carrou</a></span>
    </div>
</footer>

schitts/lecarrou/app/templates/layouts/_nav.html
{% load static i18n %}
{% load i18n %}
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark mb-4" style="background-color:#9cb58d;">
  <div class="container-fluid">
    <!--<a class="navbar-brand" href="{% url 'home' %}">Schitt's Creek Cafe Tropical</a>-->
    <a class="navbar-brand" href="">
      <img src="{% static 'images/Cafelogo.webp' %}" alt="Logo" width="50">
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li>

        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'home' %}"><i class="fa fa-home" aria-hidden="true"></i>
          {% trans 'Home' %}<span class="sr-only">(current)</span></a>
        </li>
        {% if user.is_authenticated %}
          {% if user.username == 'twyla' %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'cafe:index' %}"><i class="fa fa-cutlery" aria-hidden="true"></i>
            Orders</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'cafe:dashboard' %}"><i class="fa fa-bar-chart" aria-hidden="true"></i>
            Dashboard</a>
          </li>

          {% elif user.username == 'admin' %}
          <li class="nav-item">
            <a class="nav-link" href="/admin"><i class="fa fa-cog" aria-hidden="true"></i>
            Administration</a>
          </li>

          {% elif user.username != 'twyla' or user.username != 'admin' %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'cafe:comment_index' %}"><i class="fa fa-comment" aria-hidden="true"></i>
            Comments</a>
          </li>

          {% endif %}

        {% endif %}

        <li class="nav-item">
          <a class="nav-link" href="{% url 'contact' %}"><i class="fa fa-address-card-o" aria-hidden="true"></i>
          Contact</a>
        </li>

      </ul>

      {% if user.is_authenticated %}
      <ul class="navbar-nav">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">
            {{ user.username }}
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="#"><i class="fa fa-user-circle" aria-hidden="true"></i>
            {% trans 'Profile' %}</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{% url 'password_change' %}"><i class="fa fa-key" aria-hidden="true"></i>
            {% trans 'Change password' %}</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{% url 'logout' %}"><i class="fa fa-sign-out" aria-hidden="true"></i>
            {% trans 'Logout' %}</a>
          </div>
        </li>
      </ul>
      {% else %}
      <form class="form-inline my-2 my-lg-0">
        <a href="{% url 'login' %}" style="color:white;border-color:white;" class="btn btn-outline-secondary">{% trans 'Login' %}</a>  <a href="{% url 'registration:signup' %}"  style="color:white;border-color:white;" class="btn btn-outline-secondary">{% trans 'Signup' %}</a>
      </form>
      {% endif %}
    </div>
  </div>
</nav>

schitts/lecarrou/app/templates/layouts/base.html
{% load static %}
{% load static i18n %}
{% load widget_tweaks %}

<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">


  {% block extrahead %}{% endblock %}

  <title>{% block title %}Cafe Tropical{% endblock %}</title>

</head>

<body>
  {% include 'layouts/_nav.html' %}
  {% block content %}{% endblock %}
  <br><br><br><br><br><br>
  {% include 'layouts/_footer.html' %}

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
    crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  <!--DataTable-->
  <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
  <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js"></script>
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.css">
  <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css">
  <!--DataTable-->
  <script src="{% static 'cafe/js/jquery.formset.js' %}"></script>
  <!-- Chart.js -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.min.js"
        integrity="sha512-d9xgZrVZpmmQlfonhQUvTR7lMPtO7NkZMkA0ABN3PHCbKA5nqylQ/yWlFAyY6hYgdF1Qh6nYiuADWwKB4C2WSw=="
        crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.min.css"
        integrity="sha512-/zs32ZEJh+/EO2N1b0PEdoA10JkdC3zJ8L5FTiQu82LR9S/rOQNfQN7U59U9BC12swNeRAz3HSzIL2vpp4fv3w=="
        crossorigin="anonymous" />
  <!-- Chart.js -->
  <!--Modal-->
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  <!--Modal-->
  {% block extrabody %}{% endblock %}

  <script>
    // Code JS ajouté sur toutes les pages pour bloquer la flèche retour arrière
    // Testé sur Firefox = OK et Chrome = ne fonctionne pas
    window.onpopstate = function (e) {
      // console.log('click sur back')
      history.go(1);
    };
    history.pushState({}, '', '');

  </script>

</body>

</html>